CREATE TABLE IF NOT EXISTS poster_settings (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Title VARCHAR(255) NOT NULL,
    Description TEXT,
    Image VARCHAR(255) NOT NULL,
    IDKhuyenMai INT NOT NULL,
    MaxDisplayProducts INT NOT NULL DEFAULT 5,
    IsActive TINYINT(1) NOT NULL DEFAULT 1,
    NgayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (IDKhuyenMai) REFERENCES khuyenmai(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; 